"""empty message

Revision ID: ea685d53b38c
Revises: 
Create Date: 2024-10-21 10:39:22.397502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea685d53b38c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cctv_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cctv_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cctv_location_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cctv_location_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_cctv_location_updated_at'), ['updated_at'], unique=False)

    op.create_table('detector_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detector_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detector_type_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detector_type_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_detector_type_updated_at'), ['updated_at'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('dir', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_dir'), ['dir'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_updated_at'), ['updated_at'], unique=False)

    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('otp', sa.String(length=256), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_email'), ['email'], unique=True)

    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', 'guest', name='userrole'), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('otp_code', sa.String(length=6), nullable=True),
    sa.Column('otp_expiration', sa.DateTime(), nullable=True),
    sa.Column('penalty_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_updated_at'), ['updated_at'], unique=False)

    op.create_table('cctv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cctv_location_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cctv_location_id'], ['cctv_location.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cctv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cctv_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cctv_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cctv_updated_at'), ['updated_at'], unique=False)

    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_updated_at'), ['updated_at'], unique=False)

    op.create_table('document_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('template', sa.String(length=480), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_template_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_template_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_message_template_updated_at'), ['updated_at'], unique=False)

    op.create_table('su_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.Column('path', sa.String(length=120), nullable=True),
    sa.Column('detector_type_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detector_type_id'], ['detector_type.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_updated_at'), ['updated_at'], unique=False)

    op.create_table('detector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cctv_id', sa.Integer(), nullable=True),
    sa.Column('detector_type_id', sa.Integer(), nullable=True),
    sa.Column('weight_id', sa.Integer(), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctv.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detector_type_id'], ['detector_type.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weight_id'], ['weight.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detector_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detector_updated_at'), ['updated_at'], unique=False)

    op.create_table('detected_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detector_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('frame', sa.LargeBinary(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['detector_id'], ['detector.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detected_object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detected_object_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_detected_object_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_detected_object_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_detected_object_updated_at'), ['updated_at'], unique=False)

    op.create_table('notification_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detector_id', sa.Integer(), nullable=True),
    sa.Column('message_template_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detector_id'], ['detector.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_template_id'], ['message_template.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_rule_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_rule_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_rule_updated_at'))
        batch_op.drop_index(batch_op.f('ix_notification_rule_created_at'))

    op.drop_table('notification_rule')
    with op.batch_alter_table('detected_object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detected_object_updated_at'))
        batch_op.drop_index(batch_op.f('ix_detected_object_timestamp'))
        batch_op.drop_index(batch_op.f('ix_detected_object_name'))
        batch_op.drop_index(batch_op.f('ix_detected_object_created_at'))

    op.drop_table('detected_object')
    with op.batch_alter_table('detector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detector_updated_at'))
        batch_op.drop_index(batch_op.f('ix_detector_created_at'))

    op.drop_table('detector')
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_updated_at'))
        batch_op.drop_index(batch_op.f('ix_weight_path'))
        batch_op.drop_index(batch_op.f('ix_weight_name'))
        batch_op.drop_index(batch_op.f('ix_weight_created_at'))

    op.drop_table('weight')
    op.drop_table('user_permission')
    op.drop_table('su_menu')
    with op.batch_alter_table('message_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_template_updated_at'))
        batch_op.drop_index(batch_op.f('ix_message_template_name'))
        batch_op.drop_index(batch_op.f('ix_message_template_created_at'))

    op.drop_table('message_template')
    op.drop_table('document_permission')
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_updated_at'))
        batch_op.drop_index(batch_op.f('ix_contact_created_at'))

    op.drop_table('contact')
    with op.batch_alter_table('cctv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cctv_updated_at'))
        batch_op.drop_index(batch_op.f('ix_cctv_type'))
        batch_op.drop_index(batch_op.f('ix_cctv_created_at'))

    op.drop_table('cctv')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_name'))

    op.drop_table('permission')
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_email'))

    op.drop_table('guest')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_updated_at'))
        batch_op.drop_index(batch_op.f('ix_document_title'))
        batch_op.drop_index(batch_op.f('ix_document_dir'))
        batch_op.drop_index(batch_op.f('ix_document_created_at'))

    op.drop_table('document')
    with op.batch_alter_table('detector_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detector_type_updated_at'))
        batch_op.drop_index(batch_op.f('ix_detector_type_name'))
        batch_op.drop_index(batch_op.f('ix_detector_type_created_at'))

    op.drop_table('detector_type')
    with op.batch_alter_table('cctv_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cctv_location_updated_at'))
        batch_op.drop_index(batch_op.f('ix_cctv_location_name'))
        batch_op.drop_index(batch_op.f('ix_cctv_location_created_at'))

    op.drop_table('cctv_location')
    # ### end Alembic commands ###
